### ISSUE TITLE
bart wave -a fails, because wave does not have an option -a

### ISSUE THREAD

**Issue by xingwangyong** [mrirecon/bart-workshop#11]
```
./bart version
v0.7.00
```
In version 0.8, there is not wave -a option either.

https://github.com/mrirecon/bart-workshop/blob/2dbf66984bec33e5d0cc2ad0aa47c32129af2a5d/ismrm2016/wave-cs/demo_wave_cs.m#L105

**Comment by hcmh** [comment]
You are right, this functionality was removed in 2018. For now, you could probably use bart version v0.4.03 for that tutorial.
